apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-playground
  labels:
    app: wil42-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42-playground
  template:
    metadata:
      labels:
        app: wil42-playground
    spec:
      containers:
        - name: wil42-playground
          image: wil42/playground:v1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8888
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wil42-playground
  labels:
    app: wil42-playground
spec:
  selector:
    app: wil42-playground
  ports:
    - name: http
      port: 8888
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: wil42-playground-ingress
spec:
  routes:
  - match: Host(`192.168.56.110`)
    kind: Rule
    services:
    - name: wil42-playground
      port: 8888