apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-playground
  namespace: dev
  labels:
    app: wil42-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42-playground
  template:
    metadata:
      labels:
        app: wil42-playground
    spec:
      containers:
        - name: wil42-playground
          image: wil42/playground:v1
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8888
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  labels:
    app: wil-playground
spec:
  type: NodePort 
  ports:
  - name: 8888-8888
    nodePort: 30080
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: wil-playground
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil42-playground-ingress
  namespace: dev
spec:
  rules:
  - host: iqessam.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wil42-playground
            port:
              number: 8888
