apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-playground
  namespace: dev
  labels:
    app: wil42-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42-playground
  template:
    metadata:
      labels:
        app: wil42-playground
    spec:
      containers:
        - name: wil42-playground
          image: wil42/playground:v2
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8888
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wil42-playground-service
  namespace: dev
  labels:
    app: wil42-playground
spec:
  selector:
    app: wil42-playground
  ports:
    - name: http
      port: 8888
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil42-playground-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wil42-playground-service
            port:
              number: 8888

